### ISSUE TITLE
How To Deploy

### ISSUE THREAD

**Issue by N-SUDY** [forsyth47/Animepahe-TGBot#1]
Hello Sir How Can I Deploy this Repo and What this Repo Can Do.i just want to download anime from animepahe it's look like easy with this Repo but I don't know how to deploy or could you tell me it's there any demo bot available.

Best Regards 

Samuel

**Comment by forsyth47** [comment]
hey! sorry for the late response. This is a telegram bot, and its already hosted! you can use it from https://t.me/animepaheebot

The way in which this code scrapes links from animepahe is extremely inefficient right now. I'm working on it now, and their will be a update in upcoming 2 or 3 days! After the update, you can just use telegram bot, which will give you the direct links from animepahe, which you can use to download by using download managers like "1DM" or manually download with ffmpeg.

Feel free to get in touch with me through [telegram](https://t.me/JoshuaForsyth).
